import 'dart:async';

import 'package:build/build.dart';
import 'package:glob/glob.dart';

/// A builder that generates a barrel export file (`lib/<outputDir>.g.dart`)
/// containing `export` statements for every `.dart` file produced inside
/// `lib/<outputDir>/`.
///
/// The barrel is **fully regenerated** on every build:
/// - Added source files → their generated outputs are exported.
/// - Deleted source files → `build_runner` removes their outputs before this
///   builder runs, so stale exports never appear in the barrel.
///
/// This builder is **opt-in**. Enable it in the consumer's `build.yaml`:
///
/// ```yaml
/// targets:
///   $default:
///     builders:
///       rest_client_builder|rest_export:
///         enabled: true
///         options:
///           output_dir: generated   # must match the other three builders
/// ```
///
/// The generated barrel looks like:
/// ```dart
/// // GENERATED CODE - DO NOT MODIFY BY HAND
/// export 'package:my_app/generated/api/user_api.rest.g.dart';
/// export 'package:my_app/generated/models/user.g.dart';
/// ```
class RestExportBuilder implements Builder {
  /// Creates a [RestExportBuilder].
  ///
  /// [outputDir] is the intermediate folder under `lib/` that the other
  /// rest_client_builder builders write into (default: `generated`).
  const RestExportBuilder({this.outputDir = 'generated'});

  /// Output subfolder under `lib/` — must match the other builders.
  final String outputDir;

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$lib$': ['$outputDir.g.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    // Collect all .dart files the other builders wrote into lib/<outputDir>/.
    final glob = Glob('lib/$outputDir/**.dart');
    final assets = await buildStep.findAssets(glob).toList();

    if (assets.isEmpty) {
      return;
    }

    // Sort for deterministic output.
    assets.sort((a, b) => a.path.compareTo(b.path));

    final package = buildStep.inputId.package;
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln(
        '// Generated by rest_client_builder — '
        'regenerated on every `dart run build_runner build`.',
      )
      ..writeln();

    for (final asset in assets) {
      // asset.path is like 'lib/generated/models/user.g.dart'
      // → strip leading 'lib/' to get the package-relative path.
      final relativePath = asset.path.substring('lib/'.length);
      buffer.writeln("export 'package:$package/$relativePath';");
    }

    final outputId = AssetId(package, 'lib/$outputDir.g.dart');
    await buildStep.writeAsString(outputId, buffer.toString());
  }
}
